apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: captcha
  name: captcha
  namespace: jojoquant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: captcha
  template:
    metadata:
      labels:
        app: captcha
    spec:
      containers:
      - image: k8s.gcr.io/captcha
        name: captcha
        ports:
        - containerPort: 8666
          protocol: TCP
