# cat mysite.svc.yml 
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: mysite
  name: mysite
  namespace: jojoquant
spec:
  ports:
  - port: 8888
    targetPort: 8888
  selector:
    app: mysite
