apiVersion: v1
kind: ConfigMap
metadata:
  name: mysite-config
  namespace: jojoquant
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
      external_labels:
        clustername: test  

