version: '3.1'
services:
  frontend:
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - 5001:80
    volumes:
      - /certs/registry.crt:/etc/apache2/server.crt:ro
      - /certs/registry.key:/etc/apache2/server.key:ro
    environment:
      - ENV_DOCKER_REGISTRY_HOST=127.0.0.1
      - ENV_DOCKER_REGISTRY_PORT=5000
