Name:         mails
Namespace:    prometheus
Labels:       <none>
Annotations:  <none>

Data
====
mail.tmpl:
----
{{ define "alert.html" }}
<table border="1" cellspacing="0" bordercolor="#000000" width = "80%">
<tr>
    <td>name</td>
    <td>event</td>
    <td>start</td>
    <td>end</td>

</tr>
{{ range $i, $alert := .Alerts }}
<tr>
    <td> {{ index $alert.Annotations "policy" }} </td>
    <td> {{ index $alert.Annotations "description" }} </td>
    <td> {{ $alert.StartsAt.Format "20060102 15:04:05"}} </td>
    <td> {{ $alert.EndsAt.Format "20060102 15:04:05" }} </td>
</tr>
{{ end }}
</table>
{{ end }}

Events:  <none>
